coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
