// Package memorypack encodes and decodes the C# MemoryPack binary format.
// The format is schema-dependent: both sides must agree on field order, scalar
// widths, union tags, and whether an object uses version-tolerant encoding.
// No format-version byte is automatically prepended.
//
// # Type mapping
//
// Fixed-width Go integers map to their corresponding C# widths. Go int and uint
// use 64-bit wire values on all architectures; use int32 for a C# int. Named
// scalar types, including enums, preserve the underlying scalar representation.
// Structs use the MemoryPack object layout, not C# unmanaged struct memory layout.
// Slices and arrays use collection headers, and maps use dictionary headers.
// Map entry order is unspecified. Nil and empty slices and maps remain distinct.
//
// Strings default to UTF-8. SerializeWithOptions can select UTF16; the reader
// detects either encoding automatically. A string decodes C# null as empty;
// use *string to retain the null distinction. Go strings must contain valid
// UTF-8. Unpaired C# UTF-16 surrogates are rejected because Go has no corresponding
// Unicode scalar value.
//
// # Addresses and nullable values
//
// Serialize(&value) treats the outer pointer as the address of the wire value.
// This preserves an interface's static schema and is the recommended form for
// unions and nullable pointers. Passing a non-nil pointer directly to a scalar
// instead encodes the addressed scalar. Nullable[T] gives scalar nullability an
// explicit representation without this address distinction.
//
// Within an object or collection, a pointer to a scalar maps to C# Nullable<T>,
// including its presence flag and alignment padding. A pointer to a struct maps
// to a nullable C# object; pointers to strings and collections use their own
// four-byte null headers. Reference identity and cycles are not serialized.
//
// # Unions and object schemas
//
// RegisterUnion[T] associates an interface T with explicit UnionMember tags.
// Serialize(&interfaceValue) retains T; Serialize(interfaceValue) sees only its
// concrete Go type. Registered schemas are immutable and safe for concurrent use.
// Reader and Writer instances themselves belong to one caller at a time.
//
// Exported fields are serialized in declaration order. The memorypack:"-" tag
// omits a field, and numeric tags specify field order. Duplicate, negative, or
// malformed orders are errors. Unexported fields are omitted.
// Ordinary objects may read an older schema with fewer trailing fields, but
// cannot skip unknown fields. VersionTolerant opts a struct into length-delimited
// fields that allow additions and removals with permanent explicit field orders.
// Missing fields retain their destination values, matching C# overwrite behavior.
// Use a zero destination when missing fields should default to zero.
//
// # Custom formatters
//
// Marshaler.MarshalMemoryPack and Unmarshaler.UnmarshalMemoryPack supply custom
// wire representations independently; Formatter combines both. They run at
// every nesting level. Pointer receiver methods also work for non-addressable
// values, including map values, through a temporary copy when marshaling.
// Use Writer.WriteValue and Reader.ReadValue for nested values to preserve the
// current encoding, depth budget and collection limit.
// Nil custom pointers require an explicit nullable representation or a union,
// whose outer tag handles null. The codec cannot infer null from arbitrary
// custom payload bytes. Custom formatters are responsible for validating their
// own payloads and for bounded work within their methods.
//
// # Decoding limits and ownership
//
// Deserialize reads one value and permits trailing bytes. Reader.ReadValue can
// consume consecutive values, and Reader.Remaining reports unread bytes. Failed
// decoding may partially update the destination. CollectionLimit defaults to
// DefaultCollectionLimit and can be raised on a Reader for trusted larger inputs.
// Byte slices are bounded by available bytes; recursive decoding uses MaxDepth.
// Reader.ReadRaw borrows input bytes, while ReadBytes and decoded byte slices
// copy them. Writer.GetBytes borrows the writer buffer; WriteRaw copies input.
//
// This package does not implement C# reference tracking, compression, framework
// integration, or arbitrary unmanaged .NET struct layouts. Compatibility fixtures
// are generated by the pinned C# project under testdata/csharp.
package memorypack
